(require 'org-chef-json-ld)

(ert-deftest org-chef-json-ld-extract-recipe ()
  (let* ((json (json-read-file "json-ld-sample.json"))
         (recipe (org-chef-json-ld-extract-recipe json))
         (ingredients (cdr (assq 'recipeIngredient recipe))))
    (should (string= "PT2H" (cdr (assq 'cookTime recipe))))
    (should (eq 5 (length ingredients)))
    (should (string= "ingredient 1" (elt ingredients 0)))))

(ert-deftest org-chef-json-ld-extract-recipe-array ()
  (let* ((json (json-read-file "json-ld-sample-array.json"))
         (recipe (org-chef-json-ld-extract-recipe json))
         (ingredients (cdr (assq 'recipeIngredient recipe))))
    (should (string= "PT2H" (cdr (assq 'cookTime recipe))))
    (should (eq 5 (length ingredients)))
    (should (string= "ingredient 1" (elt ingredients 0)))))

(ert-deftest org-chef-json-ld-extract-recipe-graph ()
  (let* ((json (json-read-file "json-ld-sample-graph.json"))
         (recipe (org-chef-json-ld-extract-recipe json))
         (ingredients (cdr (assq 'recipeIngredient recipe))))
    (should (string= "PT2H" (cdr (assq 'cookTime recipe))))
    (should (eq 5 (length ingredients)))
    (should (string= "ingredient 1" (elt ingredients 0)))))

(ert-deftest org-chef-json-ld-parse-duration ()
  (should (string= "1 hour" (org-chef-json-ld-parse-duration "PT1H")))
  (should (string= "1 hour" (org-chef-json-ld-parse-duration "PT01H")))
  (should (string= "1 hour" (org-chef-json-ld-parse-duration "PT1H0M")))
  (should (string= "1 hour" (org-chef-json-ld-parse-duration "PT1H00M")))
  (should (string= "2 hours" (org-chef-json-ld-parse-duration "PT2H")))
  (should (string= "2 hours" (org-chef-json-ld-parse-duration "PT02H")))
  (should (string= "2 hours" (org-chef-json-ld-parse-duration "PT02H0M")))
  (should (string= "2 hours" (org-chef-json-ld-parse-duration "PT02H00M")))
  (should (string= "2 hours, 10 minutes" (org-chef-json-ld-parse-duration "PT02H10M")))
  (should (string= "2 hours, 10 minutes" (org-chef-json-ld-parse-duration "PT02H10M")))
  (should (string= "10 minutes" (org-chef-json-ld-parse-duration "PT0H10M")))
  (should (string= "10 minutes" (org-chef-json-ld-parse-duration "PT10M"))))

(ert-deftest org-chef-json-ld-extract-directions ()
  (should (equal (org-chef-json-ld-extract-directions "Test") '("Test")))
  (should (equal (org-chef-json-ld-extract-directions '("Foo" "Bar")) '("Foo" "Bar")))
  (should (equal (org-chef-json-ld-extract-directions
                  '(((text . "Foo"))
                    ((text . "Bar"))))
                 '("Foo" "Bar"))))

(ert-deftest org-chef-json-ld-extract-json-ld ()
  (let* ((dom (with-temp-buffer
                (insert-file "json-ld.html")
                (libxml-parse-html-region (point-min) (point-max))))
         (json-lds (org-chef-json-ld-extract-json-ld dom)))
    (should (equal 1 (length json-lds)))))
